### ISSUE TITLE
As for the installation of StrTrak

### ISSUE THREAD

**Issue by BurinkiWU** [zheminzhou/StrTrak#4]
To whom it concerns:

I met some issues while installing the StrTrak, as the following shows:
#
Traceback (most recent call last):
  File "/home/wuzq-cdc/tools/StrTrak/./StrTrak", line 2, in <module>
    import strBase, strPhylo, strProfile
  File "/home/wuzq-cdc/tools/StrTrak/strBase.py", line 1, in <module>
    import os, gzip, click, glob, re, igraph
ModuleNotFoundError: No module named 'igraph'
#
Actually, I have installed these packages in conda env. There are listed below:
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.12               h4ab18f5_0    conda-forge
arpack                    3.9.1           nompi_h77f6705_101    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
aws-c-auth                0.7.22               h96bc93b_2    conda-forge
aws-c-cal                 0.6.14               h88a6e22_1    conda-forge
aws-c-common              0.9.19               h4ab18f5_0    conda-forge
aws-c-compression         0.2.18               h83b837d_6    conda-forge
aws-c-event-stream        0.4.2               ha47c788_12    conda-forge
aws-c-http                0.8.1               h29d6fba_17    conda-forge
aws-c-io                  0.14.8               h21d4f22_5    conda-forge
aws-c-mqtt                0.10.4               h759edc4_4    conda-forge
aws-c-s3                  0.5.9                h594631b_3    conda-forge
aws-c-sdkutils            0.1.16               h83b837d_2    conda-forge
aws-checksums             0.1.18               h83b837d_6    conda-forge
aws-crt-cpp               0.26.9               he3a8b3b_0    conda-forge
aws-sdk-cpp               1.11.329             hba8bd5f_3    conda-forge
bindash                   2.3                  hdcf5f25_2    bioconda
biopython                 1.83            py311h459d7ec_0    conda-forge
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cramjam                   2.8.3           py311h46250e7_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
emboss                    6.6.0               h1617ff0_10    bioconda
ete3                      3.1.3              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
fastparquet               2024.5.0        py311h18e1886_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2024.6.0           pyhff2d567_0    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glib                      2.80.2               hf974151_0    conda-forge
glib-tools                2.80.2               hb6ce0ca_0    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
gst-plugins-base          1.24.4               h9ad1361_0    conda-forge
gstreamer                 1.24.4               haf2f30d_0    conda-forge
harfbuzz                  8.5.0                hfac3d4d_0    conda-forge
hmmer                     3.4                  hdbdd923_1    bioconda
htslib                    1.20                 h5efdd21_1    bioconda
icu                       73.2                 h59595ed_0    conda-forge
igraph                    0.10.12              hef0740d_1    conda-forge
iqtree                    2.3.4                hdcf5f25_2    bioconda
k8                        0.2.5                hdcf5f25_4    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_h59595ed_0    conda-forge
libarrow                  16.1.0           hcb6531f_6_cpu    conda-forge
libarrow-acero            16.1.0           hac33072_6_cpu    conda-forge
libarrow-dataset          16.1.0           hac33072_6_cpu    conda-forge
libarrow-substrait        16.1.0           h7e0c224_6_cpu    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libclang-cpp15            15.0.7          default_h127d8a8_5    conda-forge
libclang13                18.1.7          default_h087397f_0    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.8.0                hca28451_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.2.0              h77fa898_11    conda-forge
libgcrypt                 1.10.3               hd590300_0    conda-forge
libgd                     2.3.3                h119a65a_9    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0              h69a702a_11    conda-forge
libgfortran5              13.2.0              h3d2ce59_11    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   13.2.0              h77fa898_11    conda-forge
libgoogle-cloud           2.24.0               h2736e30_0    conda-forge
libgoogle-cloud-storage   2.24.0               h3d9a0c8_0    conda-forge
libgpg-error              1.49                 h4f305b6_0    conda-forge
libgrpc                   1.62.2               h15f2491_0    conda-forge
libharu                   2.4.4                h267a509_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libllvm15                 15.0.7               hb3ce162_4    conda-forge
libllvm18                 18.1.7               hb77312f_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libparquet                16.1.0           h6a7eafb_6_cpu    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.3                 ha72fbe1_0    conda-forge
libprotobuf               4.25.3               h08a7969_0    conda-forge
libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
libsndfile                1.2.2                hc60ed4a_1    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0              hc0a3c3a_11    conda-forge
libsystemd0               255                  h3516f8a_1    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.4.0                h2c329e2_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h662e7e4_0    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvmlite                  0.42.0          py311ha6695c7_1    conda-forge
lxml                      5.2.2           py311hc0a218f_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
minimap2                  2.28                 he4a0461_1    bioconda
mpg123                    1.32.6               h59595ed_0    conda-forge
mysql-common              8.3.0                hf1915f5_4    conda-forge
mysql-libs                8.3.0                hca2cd23_4    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.98                 h1d7d5a4_0    conda-forge
numba                     0.59.1          py311h96b013e_0    conda-forge
numpy                     1.26.4          py311h64a7726_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
orc                       2.0.1                h17fec99_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py311h14de704_1    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
pip                       24.0            py311h06a4308_0  
pixman                    0.43.2               h59595ed_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio-client         17.0                 hb77b528_0    conda-forge
pyarrow                   16.1.0          py311h781c19f_1    conda-forge
pyarrow-core              16.1.0          py311h8e2c35d_1_cpu    conda-forge
pyqt                      5.15.9          py311hf0fb5b6_5    conda-forge
pyqt5-sip                 12.12.2         py311hb755f60_5    conda-forge
python                    3.11.8          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qt-main                   5.15.8              hc9dc06e_21    conda-forge
re2                       2023.09.01           h7f4b329_2    conda-forge
readline                  8.2                  h5eee18b_0  
s2n                       1.4.15               he19d79f_0    conda-forge
samtools                  1.20                 h50ea8bc_0    bioconda
scipy                     1.13.1          py311h517d4fd_0    conda-forge
setuptools                69.5.1          py311h06a4308_0  
sip                       6.7.12          py311hb755f60_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                hdb0a2a9_1    conda-forge
sqlite                    3.45.2               h2c6b66d_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h04d1e81_0  
wheel                     0.43.0          py311h06a4308_0  
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xkeyboard-config          2.42                 h4ab18f5_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.6                h5eee18b_1  
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

Best regards,
Bruce

**Comment by BurinkiWU** [comment]
I have fixed this problem. 

For your information:
When you install the requirement package of igraph, it is better to use the following command - "pip install python_igraph" under the environment of "strtrak".
